export enum ChartGroupsEnum {
  General = 'general',
  XAxisLabelsColor = 'xAxisLabelsColor',
  XAxisLabelsFont = 'xAxisLabelsFont',
  XAxisLabelsPlacement = 'xAxisLabelsPlacement',
  XAxisBubbleLabelsPlacement = 'XAxisBubbleLabelsPlacement',
  XAxisTitle = 'xAxisTitle',
  YAxisLabelsColor = 'yAxisLabelsColor',
  YAxisLabelsFont = 'yAxisLabelsFont',
  YAxisLabelsPlacement = 'yAxisLabelsPlacement',
  Y2AxisTitle = 'Y2AxisTitle',
  Y2AxisLabelsColor = 'Y2AxisLabelsColor',
  Y2AxisLabelsFont = 'Y2AxisLabelsFont',
  Y2AxisLabelsPlacement = 'Y2AxisLabelsPlacement',
  Y2Axis = 'y2Axis',
  YAxisTitle = 'yAxisTitle',
  XAxis = 'xAxis',
  XValueAxis = 'xValueAxis',
  YAxis = 'yAxis',
  DataLabels = 'dataLabels',
  DataPoints = 'dataPoints',
  Titles = 'titles',
  Legends = 'legends',
  TileSectionSettings = 'tileSectionSettings',
  YAxisDataModifier = 'yAxisDataModifier',
  Y2AxisDataModifier = 'y2AxisDataModifier',
  DisplayUnits = 'DisplayUnits',
  MapDataLabels = 'MapDataLabels'

}
