export enum MenuItemNames {
    Save = 'Save',
    SaveAs = 'SaveAs',
    Delete = 'Delete',
    Rename = 'Rename',
    Options = 'Options',
    Publish = 'Publish',
    Unpublish = 'Unpublish',
    Schedule = 'Schedule',
    Export = 'Export',
    Print = 'Print',
    Info = 'Info',
    MoveTo = 'MoveTo',
    Star = 'Star',
    Link = 'Link',
    Unselect = 'Unselect',
    File = 'File',
    Tools = 'Tools',
    Help = 'Help',
    Remove = 'Remove',
    ListItem = 'ListItem',
    Edit = 'Edit',
    MergeReport = 'Merge Report',
    EditReport = 'EditReport'
}
